### PR TITLE
Update readme to accurately reflect the current build process for a local copy of the manual

### PR DESCRIPTION
**Pull request by StillLearnin**

### CODE REVIEW

**Comment by StillLearnin** [comment]
@pauldavisthefirst I suppose you automatically get notified of pull requests? If not, here's your notification.

**Comment by StillLearnin** [comment]
Any comments? Using the steps outlined in this pull request I set up a local manual on a brand new virtual machine and verified that it works. Using the information in the existing readme doesn't work so I think this is an improvement and should be merged even though it will probably become obsolete eventually.

**Comment by pauldavisthefirst** [comment]
I want to apply this, but it seems to have become stale. Manually applying the patch fails in almost all cases.

**Comment by StillLearnin** [comment]
Any possibility of using github as the main repository for the manual? Github still reports it as being able to automatically merge and if github were the main repository it could be merged cleanly with one click.

**Comment by StillLearnin** [comment]
Sorry, that would be two clicks...

**Comment by pauldavisthefirst** [comment]
github is mirrored automatically from git.ardour.org. I'm unwilling to use
github as the canonical repository.

I don't understand how github thinks it can merge when git merge reports
almost every patch hunk failing. It sounds to me as if I should just copy
README.md from your branch.

**Comment by StillLearnin** [comment]
>  I'm unwilling to use github as the canonical repository.

Ok.

Yes, just grab the README.md.

**Comment by StillLearnin** [comment]
Would it make it easier for you if I would close this pull request and create a new one with just one commit?

**Comment by pauldavisthefirst** [comment]
Sure. Thanks.

**Comment by StillLearnin** [comment]
Closing this PR to create a new one.

**Pull request closed without merging**
