### PR TITLE
Some smaller fixes

### PR DESCRIPTION
**Pull request by derwok**

### CODE REVIEW

**Review by pauldavisthefirst — APPROVED** [review]

**Review by pauldavisthefirst — CHANGES_REQUESTED** [review]
this file is automatically generated, so we do not accept PRs for it. new versions were recently generated. can you remove this from the branch?

**Comment by derwok** [comment]
Removed the `mnemonic-bindings-for-linux.html`from this pull request

**Comment by derwok** [comment]
Hmmm... almost 1 year unmerged?
Anything I can do here?

**Comment by ovenwerks** [comment]
Sorry, this will not rebase on top of master. (probably not your fault) The merge conflicts are too many for me to resolve, it may be easier to close this and put these edits on top of master

**Comment by derwok** [comment]
Yes probably due to 1 year old PR. 
Nevermind! I'll have look.

**Comment by derwok** [comment]
Created new PR from current master
see https://github.com/Ardour/manual/pull/198

**Pull request closed without merging**
