### PR TITLE
Added 6.6 show automation on touch + minor "transforming midi" changes

### PR DESCRIPTION
**Pull request by MrHeadwar**

### CODE REVIEW

**Comment by MrHeadwar** [comment]
Since the original PR, :
- review/update of the whole main menu
- corrected a minor bug in the doc (0008648)
- updated the Region List
- added a description of the new Virtual MIDI Keyboard
- removed the link to the PDF version if no pdf is generated (fixing the 404 bug in a way as future-proof as possible)

**Comment by MrHeadwar** [comment]
- updated the preferences page
- updated the favorite plugins page

**Comment by MrHeadwar** [comment]
- Added the two new items of the toolbar
- Updated the Status Bar description

**Comment by MrHeadwar** [comment]
- A touch of CSS, image titles text was larger than content text
- The Toolbar has been updated
- Added a page about the LAN, that I hope is clear and thorough

**Comment by ovenwerks** [comment]
Merged.

**Pull request closed without merging**
