### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by hotguac**
Fix multiple broken links found with online link checker.

### CODE REVIEW

**Comment by hotguac** [comment]
Sorry about all the changes with the spaces stripped at end of line. I didn't notice those changes until I posted.  I can cancel this request and redo the link fixes with an editor set to not strip the spaces if that would be cleaner.

**Comment by pauldavisthefirst** [comment]
Much better to have spaces stripped off, thanks. Unless I'm not
understanding what you mean.

**Comment by hotguac** [comment]
That's what I meant.

**Comment by hotguac** [comment]
I unintentionally added another commit to this pull request. I'm working on a modification to the build.rb script to create a PDF version of the manual. I've tested commit dfeff04 and don't think it would be a problem to merge, but *I can back it out if you want*.  To test the changes: running './build.rb' with no parameters behaves the same as before this commit. Running './build.rb -h' will create the PDF in 'source/file/'.  Requires the 'wkhtmltopdf' utility installed from http://wkhtmltopdf.org/downloads.html in order to build the PDF. It still needs a cover page added with logo and copyright.

**Comment by hotguac** [comment]
Intended use, build hardcopy, build regular to include the hardcopy, upload
build -h
build
upload

**Comment by hotguac** [comment]
I'll rework this request.

**Pull request closed without merging**
