### PR TITLE
Various manual edits

### PR DESCRIPTION
**Pull request by jedslater**
Typo fixes, improving readability, conforming to the style guide, etc.

### CODE REVIEW

**Comment by ovenwerks** [comment]
In  "include/export-format-profiles.html", "Ranges &amp; Marks" is an actual tab name and should remain &.
 include/lua-scripting.html should have it's lines wrapped so they can be read easily on github and in most editors... I know not your mistake :) I am not sure Robin would agree with changing all the lua to Lua, the correct name may be all lower case just like c or c++. I will wait for his comment.

**Comment by x42** [comment]
Looks good to me. "Lua - the programming language"  is correctly written with a capital "L"  (and only a capital L, not LUA, nor lua)

As for line-wrap that'll ideally be a separate commit  "NO-OP: whitespace".

PS. The correct spelling for "C++" is also a capital "C".

**Comment by ovenwerks** [comment]
Actually there are no conflicts and this PR has been merged. Jedslater, when you force your branch to be the same as master, this will close on it's own. I don't have access to do that here :)

**Comment by jedslater** [comment]
@ovenwerks I've resolved all conflicts in accordance with the new line breaks from "NO-OP: whitespace". It should look right now!

**Comment by ovenwerks** [comment]
@jedslater Actually it is already merged. But because of the route merging takes... github does not show it as such. I can't close the pr, but if you pull master you should see your changes have been added. Thank you.

**Comment by pauldavisthefirst** [comment]
manually merged.

**Pull request closed without merging**
