### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by Ardeshir81**
List of all changes:
  - minor linting: semicolons removed in python
  - added an icon beside github icon for switching between light and dark theme dynamically. unlike github link, this theme changer exists in all pages (even table of contents)
  - changed github link from `` to `background-image` to be able to change it with css
  - added some javascript to handle setting css classes for dark-theme
  - avoided some inline styles, to make them themeable through css
  - added some css for styling things when in dark mode
  - added three new images, one for github in dark mode, two for themechanger (in dark & light mode)

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Not bad!

The bg color of the LHS "contents" list seems a bit incongruous to me when in "dark mode"

**Comment by Ardeshir81** [comment]
Thanks @pauldavisthefirst 
Unfortunately I don't know where that **LHS 'contents'** is, but searching for that, I did some random improvements.

**Comment by Ardeshir81** [comment]
Hey @pauldavisthefirst
Could you please point me to page you saw inharmonic 

A screenshot could be great

**Comment by Ardeshir81** [comment]
hey @pauldavisthefirst can you guide me to where exactly the problem is so I can fix it?
At nights, it is so hard to read the manual when lights are off

**Comment by pauldavisthefirst** [comment]
The LHS Contents is just the vertical list of contents (expandable) that is on the left hand side of each page.

**Comment by Ardeshir81** [comment]
Is it better now @pauldavisthefirst ?

**Comment by pauldavisthefirst** [comment]
Did you delete your dark theme repository? I'm finally doing a merge/rebase of a bunch of manual PRs and it seems yours is gone?

**Comment by pauldavisthefirst** [comment]
Actually, I've checked a couple of dark-theme extensions for google and firefox and I think they do a better job than this customized set of changes. Thanks very much for the effort and idea - sorry it didn't work out.

**Comment by Ardeshir81** [comment]
Thanks Paul. I think yes, I've removed the forked repository by mistake. I was cleaning up my GitHub profile (It's new year in Iran :) ) and I probably have forgotten that I had an open merge request. :)

Yes! I think those extensions would do. But if anytime you felt like needing custom dark theme, feel free to reach out. I'm a Web-Application Front-End Developer :+1:

**Comment by aghArdeshir** [comment]
Hey @pauldavisthefirst do you still think a built-in customized dark theme for manual is useless?

**Pull request closed without merging**
